language: java
jdk:
  - openjdk14

install:
  true
dist: xenial
os:
  - linux

services:
  - postgresql
before_install:
  - psql -c 'create database dreamjob;' -U postgres

addons:
  sonarcloud:
    organization: "mi1qw"
    token: ${SONAR_TOKEN}
    #    branches:
    #      - master

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  #  - mvn clean install sonar:sonar -Dsonar.projectKey=mi1qw_job4j_dreamjob

  #  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=mi1qw_job4j_dreamjob

  # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
#  - mvn clean verify sonar:sonar -Pcoverage

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache

## после выполнени¤ сборки запустить скрипт, который будет собирать статистику по JaCoCo
after_success:
  - mvn clean install
  #  - mvn clean test jacoco:report coveralls:report -X

  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)
  #  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/jacoco/jacoco.xml


# отправл¤ть уведомление на почтуyouremail@smtp.ru(»зменить на свою) если сборка упала
notifications:
  webhooks: https://coveralls.io/webhook
  email:
    recipients: "-123mib@gmail.com"
    on_success: always # default: change
    on_failure: always # default: always

env:
  global:
  - CODECOV_TOKEN="fa2c926f-3db5-488c-9a50-4e1e4fdf6913"
  - TRAVIS_NODE_VERSION="10"